### ISSUE TITLE
Passing string to float parameter when setting brush size

### ISSUE THREAD

**Issue by jasonwynn10** [BlockHorizons/BlockSniper#68]
#### Description

Running the command `/brush size 3` causes an error.
#### Versions
* PocketMine version: API unlocked 3.0.0-ALPHA7
* BlockSniper version: 1.4.0
* Game version: N/A

#### Crashdump and/or console errors

```
03.09 19:42:13 [Server] Server thread/CRITICAL TypeError: "Argument 1 passed to BlockHorizons\BlockSniper\brush\Brush::setSize() must be of the type float, string given, called in phar:///plugins/BlockSniper.phar/src/BlockHorizons/BlockSniper/commands/BrushCommand.php on line 109" (EXCEPTION) in "BlockSniper.phar/src/BlockHorizons/BlockSniper/brush/Brush" at line 118
03.09 19:42:13 [Server] Server thread/CRITICAL Unhandled exception executing command 'brush size 3' in brush: Argument 1 passed to BlockHorizons\BlockSniper\brush\Brush::setSize() must be of the type float, string given, called in phar:///plugins/BlockSniper.phar/src/BlockHorizons/BlockSniper/commands/BrushCommand.php on line 109
```

**Comment by Sandertv** [comment]
The sad truth is that BlockSniper is a bit of a walking corpse waiting to be revived. It's not stable at all in the current version, but I don't want to waste time on it because I've fixed it on another branch. (Where have I heard this before? api3/blocks? 😄 ) I would recommend that version, if only it worked for 1.1... which it doesn't, because it uses 1.2 only features.

**Comment by jasonwynn10** [comment]
Is 1.5 able to work on 1.1 servers?

**Comment by Sandertv** [comment]
I can't say it's really usable for 1.1 no. 😕

**Comment by Sandertv** [comment]
The latest version is usable on 1.2 servers. Be careful when it comes to undoing changes with a brush size higher than 15; It won't work yet.
